# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IMDB Search' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IMDB Search
  pod 'SDWebImage', '~> 5.0'
  pod 'IQKeyboardManagerSwift'
end
